FROM ubuntu:18.04

USER root

WORKDIR /home/project

RUN apt-get update
RUN apt install -y git
RUN apt-get -y install curl gnupg

RUN curl -sL https://deb.nodesource.com/setup_12.x  | bash -

RUN apt-get -y install nodejs

RUN npm install -g typescript
